In [2]:
import os, copy, sys
import numpy as np
import pandas as pd
from typing import List, Tuple

In [3]:
# Run this cell to remove pool_alice_code from package namespace, and reimport it with most recent changes
sys.modules.pop("pool_alice_code",None)
import pool_alice_code_NO_BATCH_CORRELATION as pool_alice_code

# Load data and explore a little (note: most of the exploration is in the "automation_final_project/data" under the respective datasets)

In [4]:
os.getcwd()

'/home/ethan/02750-automation/automation_final_project/P_ALICE'

In [5]:
X: np.ndarray = np.load('../data/logd74/fingerprints.npy')
y: np.ndarray  = np.load('../data/logd74/logd74s.npy')

X_df = pd.DataFrame(X)
print(X_df.shape)
X_df.head()

(1130, 2048)


0     1     2     3     4     5     6     7     8     9     ...  2038  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   2039  2040  2041  2042  2043  2044  2045  2046  2047  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 2048 columns]

In [6]:
X_df.describe()

0            1            2            3            4     \
count  1130.000000  1130.000000  1130.000000  1130.000000  1130.000000   
mean      0.000885     0.238053     0.069027     0.011504     0.022124   
std       0.029748     0.426080     0.253612     0.106687     0.147152   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              5            6            7            8            9     ...  \
count  1130.000000  1130.000000  1130.000000  1130.000000  1130.000000  ...   
mean      0.026549     0.002655     0.007965     0.007965     0.030973  ...   
std       0.160831     0.051480     0.088928     0.088928     0.173322  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              2038    2039    2040         2041         2042         2043  \
count  1130.000000  1130.0  1130.0  1130.000000  1130.000000  1130.000000   
mean      0.024779     0.0     0.0     0.021239     0.010619     0.006195   
std       0.155519     0.0     0.0     0.144244     0.102548     0.078497   
min       0.000000     0.0     0.0     0.000000     0.000000     0.000000   
25%       0.000000     0.0     0.0     0.000000     0.000000     0.000000   
50%       0.000000     0.0     0.0     0.000000     0.000000     0.000000   
75%       0.000000     0.0     0.0     0.000000     0.000000     0.000000   
max       1.000000     0.0     0.0     1.000000     1.000000     1.000000   

              2044         2045         2046         2047  
count  1130.000000  1130.000000  1130.000000  1130.000000  
mean      0.007965     0.019469     0.011504     0.011504  
std       0.088928     0.138228     0.106687     0.106687  
min       0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000  

[8 rows x 2048 columns]

In [7]:
# https://stackoverflow.com/questions/17071871/how-do-i-select-rows-from-a-dataframe-based-on-column-values
description = X_df.describe().transpose()

zero_std = description.loc[description['std'] == 0]

zero_std

count  mean  std  min  25%  50%  75%  max
10    1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
19    1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
22    1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
44    1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
55    1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
...      ...   ...  ...  ...  ...  ...  ...  ...
1987  1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
1996  1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
2015  1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
2039  1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
2040  1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0

[95 rows x 8 columns]

In [8]:
bad_features = zero_std.transpose().columns
zero_std.transpose().columns

Index([  10,   19,   22,   44,   55,   86,  101,  127,  148,  152,  161,  167,
        178,  181,  188,  228,  229,  256,  267,  285,  324,  332,  356,  388,
        393,  417,  439,  445,  468,  492,  505,  509,  532,  572,  605,  608,
        619,  659,  662,  685,  733,  740,  818,  866,  877,  920,  923,  934,
        938,  945,  956,  986,  988,  995, 1072, 1098, 1111, 1115, 1122, 1177,
       1186, 1247, 1259, 1315, 1345, 1406, 1500, 1529, 1545, 1558, 1562, 1595,
       1628, 1641, 1644, 1686, 1703, 1709, 1720, 1740, 1784, 1787, 1793, 1834,
       1846, 1869, 1874, 1881, 1931, 1955, 1987, 1996, 2015, 2039, 2040],
      dtype='int64')

In [9]:
X_df = X_df.drop(labels=bad_features,axis=1)
print(X_df.shape)
X_df.head()

(1130, 1953)


0     1     2     3     4     5     6     7     8     9     ...  2036  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   2037  2038  2041  2042  2043  2044  2045  2046  2047  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 1953 columns]

In [10]:
X = X_df.to_numpy()
num_original_features = len(X[0])

# constants

In [11]:
SEEDS = [i*1001 for i in range(1,6)]

SEEDS

[1001, 2002, 3003, 4004, 5005]

In [12]:
BATCH_SIZE = 16

# P-ALICE, weighted linear regression

In [13]:
X_pool_linear = np.vstack((X.T,np.ones(len(X)))).T
X_pool_linear

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [14]:
num_features_linear = len(X_pool_linear[0])
basis_funcs_linear: List[np.ufunc] = [pool_alice_code.identity_basis for _ in range(num_features_linear)] # type: ignore
try:
    logd74_linear_palice_16: np.ndarray = np.load('../results/logd74_linear_palice_16.npy')
    print("RESULTS ALREADY OBTAINED\n Note, TOTAL Elapsed Time: 12290.656833171844 seconds (204.84428055286406 min)")
except:
    logd74_linear_palice_16 = pool_alice_code.simulate_pool_alice_n_times(n=len(SEEDS),seeds=SEEDS,X_pool=X_pool_linear,y_pool=y,basis_funcs=basis_funcs_linear,batch_size=BATCH_SIZE,passive_learning=False)
    np.save('../results/logd74_linear_palice_16.npy', logd74_linear_palice_16)

RESULTS ALREADY OBTAINED
 Note, TOTAL Elapsed Time: 12290.656833171844 seconds (204.84428055286406 min)


In [15]:
# check the results are consistent with expectation

x_train_length = len(X)*0.8
twenty_percent = int(x_train_length * 0.20)
fifty_percent = int(x_train_length * 0.5)
num_samples_axis = range(twenty_percent,fifty_percent+1,BATCH_SIZE)
print(num_samples_axis)
print(len(num_samples_axis))

range(180, 453, 16)
18


In [16]:
assert logd74_linear_palice_16.shape[1] == len(num_samples_axis), "The number of iterations is off"

logd74_linear_palice_16.shape

(5, 18)

# passive (random) learning, linear regression

In [17]:
try:
    logd74_linear_random_16: np.ndarray = np.load('../results/logd74_linear_random_16.npy')
    print("RESULTS ALREADY OBTAINED\nNOTE: TOTAL Elapsed Time: 1129.4733316898346 seconds (18.82455552816391 min)")
except:
    logd74_linear_random_16 = pool_alice_code.simulate_pool_alice_n_times(n=len(SEEDS),seeds=SEEDS,X_pool=X_pool_linear,y_pool=y,basis_funcs=basis_funcs_linear,passive_learning=True,batch_size=BATCH_SIZE)
    
    np.save('../results/logd74_linear_random_16.npy', logd74_linear_random_16)

RESULTS ALREADY OBTAINED
NOTE: TOTAL Elapsed Time: 1129.4733316898346 seconds (18.82455552816391 min)


# P-ALICE, nonlinear regression 1

## define basis functions for nonlinear regression 1

In [18]:
dummy = np.array([1,0,1,0])
print(dummy)

pool_alice_code.map_to_off_on_basis(dummy) # now, not having a certain motif can be penalized

[1 0 1 0]


array([ 1, -1,  1, -1])

In [19]:
X_pool_nonlinear_1 = np.vstack((X.T,np.ones(len(X)))).T
X_pool_nonlinear_1

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [20]:
basis_funcs_nonlinear_1: List[np.ufunc] = [pool_alice_code.map_to_off_on_basis for i in range(0,len(X_pool_nonlinear_1[0]))] # type: ignore
basis_funcs_nonlinear_1[-1] = pool_alice_code.identity_basis # type: ignore

assert len(X_pool_nonlinear_1[0]) == len(basis_funcs_nonlinear_1), f"len(X_pool_nonlinear_1[0]) == len(basis_funcs_nonlinear_1) is not true for {len(X_pool_nonlinear_1[0])} == {len(basis_funcs_nonlinear_1)}"

## perform PALICE for nonlinear regression 1

In [21]:
try:
    logd74_nonlinear_palice_16: np.ndarray = np.load('../results/logd74_nonlinear_palice_16.npy')
    print("RESULTS ALREADY OBTAINED\n Note, TOTAL Elapsed Time: 11185.348386764526 seconds (186.4224731127421 min)")
except:
    logd74_nonlinear_palice_16 = pool_alice_code.simulate_pool_alice_n_times(n=len(SEEDS),seeds=SEEDS,X_pool=X_pool_nonlinear_1,y_pool=y,basis_funcs=basis_funcs_nonlinear_1,batch_size=BATCH_SIZE,passive_learning=False)
    np.save('../results/logd74_nonlinear_palice_16.npy', logd74_nonlinear_palice_16)

RESULTS ALREADY OBTAINED
 Note, TOTAL Elapsed Time: 11185.348386764526 seconds (186.4224731127421 min)


# random (passive), nonlinear regression 1

In [22]:
try:
    logd74_nonlinear_random_16: np.ndarray = np.load('../results/logd74_nonlinear_random_16.npy')
    print("RESULTS ALREADY OBTAINED\nNOTE: TOTAL Elapsed Time: 812.0736465454102 seconds (13.534560775756836 min)")
except:
    logd74_nonlinear_random_16 = pool_alice_code.simulate_pool_alice_n_times(n=len(SEEDS),seeds=SEEDS,X_pool=X_pool_nonlinear_1,y_pool=y,basis_funcs=basis_funcs_nonlinear_1,passive_learning=True,batch_size=BATCH_SIZE)
    
    np.save('../results/logd74_nonlinear_random_16.npy', logd74_nonlinear_random_16)

RESULTS ALREADY OBTAINED
NOTE: TOTAL Elapsed Time: 812.0736465454102 seconds (13.534560775756836 min)


# Get the batch_size 32 results

In [23]:
print(len(num_samples_axis))
print(len(list(num_samples_axis[::2])))
logd74_nonlinear_random_16.shape

18
9


(5, 18)

In [24]:
logd74_nonlinear_random_16[:,::2].shape

(5, 9)

In [27]:
try:
    np.load('../results/logd74_linear_random_32.npy')
except:
    print("this happened")
    np.save('../results/logd74_linear_palice_32.npy',logd74_linear_palice_16[:,::2])
    np.save('../results/logd74_linear_random_32.npy',logd74_linear_random_16[:,::2])
    np.save('../results/logd74_nonlinear_palice_32.npy',logd74_nonlinear_palice_16[:,::2])
    np.save('../results/logd74_nonlinear_random_32.npy',logd74_nonlinear_random_16[:,::2])

this happened
